env:
  global:
    - secure: FxpoMJmkjBKy0qsPMLcs9fpiquJ217s5qlRC9sCTf7GWkDydqDV8ZAIy9LihOf17qH/m0U8Ii6BmOeH/V0Oa1CPhTvHVrLw+aBN6OrMWUs9EmPqa7pCpk+p6Rr81/matzfbKjTGBsSqFMAj5Aj4VpR7RTyQEBh+cZgORgbrnatU=
    - secure: QS9IQXvglj/DPaqY69AEEegEylJ/7dyqElm++LQMsOrfVCr1MUnPo2xBqciThsrBSQsqP+Llc+xGWK+/iFTxHgHhJuvcZmyZb9i+M0ISqoJkluZwZjIzYcBe3N7mo36JKqBzIkTgVvvkXPr5pn8PmYVKlgIzV2QbYRT42NIFn4U=
matrix:
  include:
    - language: java
      jdk:
        - openjdk8
      branches:
        except:
          - gh-pages
      cache:
        directories:
          - "$HOME/.m2/repository"
      before_script: sed -i "s@-dev@-dev#$TRAVIS_BUILD_NUMBER@" BetonQuest-core/src/main/resources/plugin.yml
      install: true
      script: mvn clean package -Drelease
      after_success:
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
          curl -F "pass=$pass" -F "id=$TRAVIS_BUILD_NUMBER" -F "hash=$TRAVIS_COMMIT" -F "branch=$TRAVIS_BRANCH" -F "plugin=@target/BetonQuest.jar" https://betonquest.pl;
          chmod +x scripts/discord.sh;
          scripts/discord.sh;
          fi
    - language: python
      python: 3.6
      branches:
        except:
          - gh-pages
      cache:
        pip: true
      script:
        - if [ -n "${DEPLOY_KEY}" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then
          chmod +x scripts/deploy-docs.sh;
          scripts/deploy-docs.sh;
          fi;